/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public int sum(int a, int b) {
    	return a + b;
    }
    public int multiply(int a, int b) {
    	return a * b;
    }
}
